name: memo_car
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  camera: ^0.10.0
  cloud_firestore: ^3.4.2
  dartdoc: ^6.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.6.1
  firebase_auth_mocks: ^0.8.5+1
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
  - assets/icons/
